apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: devopsportal 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devopsportal 
    spec:
      containers:
        - name: devopsportal 
          image: gammawebuk.azurecr.io/devopsportal 
          ports:
          - containerPort: 80